import sys
str1 = input()
str2 = input()
str3 = input()
A = input()
B = input()
C = input()
print("size of", str1,"=", str(sys.getsizeof(str1))+ "byte")
print("size of", str2,"=", str(sys.getsizeof(str2))+ "byte")
print("size of", str3,"=", str(sys.getsizeof(str3))+ "byte")
print("size of", A, "=", str(sys.getsizeof(A))+ "byte")
print("size of", B, "=", str(sys.getsizeof(B))+ "byte")
print("size of", C, "=", str(sys.getsizeof(C))+ "byte")